# -*- coding: utf-8 -*-
"""ass_unsup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D7j-TVVWHDzh0fuGROXrz_x2rLeaxdjg
"""

import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, DBSCAN
from sklearn.metrics import silhouette_score
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster

from sklearn.decomposition import PCA

data=pd.read_excel("/content/marketing_campaign.xlsx")
data.head()

df = data.copy()
df['Age'] = 2025 - df['Year_Birth']
df['TotalChildren'] = df['Kidhome'] + df['Teenhome']
df['TotalSpent'] = df[['MntWines', 'MntFruits', 'MntMeatProducts',
                       'MntFishProducts', 'MntSweetProducts', 'MntGoldProds']].sum(axis=1)

df.shape

#1. Load and clean the dataset (remove NA, duplicates).

df = df.dropna().reset_index(drop=True)
print("After dropna shape:", df.shape)

df = df.drop_duplicates().reset_index(drop=True)
print("After drop shape:", df.shape)



#2. Visualize spending patterns and demographics.

num = df.select_dtypes(include=[np.number]).copy()
print("Numeric columns detected:", list(num.columns))

plt.figure(figsize=(12,5))
if "Income" in df.columns:
    sns.histplot(df["Income"], kde=True)
    plt.title("Income distribution")
    plt.show()

spend_cols = [c for c in df.columns if any(x in c.lower() for x in ["mnt","amount","spend","spending","money"])]
spend_cols = spend_cols[:8]  # limit for visuals
if spend_cols:
    plt.figure(figsize=(12,6))
    df[spend_cols].sum().sort_values(ascending=False).plot.bar()
    plt.title("Total spend by category (detected)")
    plt.ylabel("Total")
    plt.show()

#Demographics - Age distribution (if Year_Birth present)
if "Year_Birth" in df.columns:
    df["Age"] = 2025 - df["Year_Birth"]  # adjust year if you want current year
    plt.figure(figsize=(8,4))
    sns.histplot(df["Age"], bins=20)
    plt.title("Age distribution")
    plt.show()

df.head()



#3. Normalize numerical features (spending, income).

drop_like = ["id", "customer", "dt_customer", "date", "email", "address"]
features = [c for c in df.columns if (c not in drop_like) and (df[c].dtype in [np.int64, np.float64])]

# remove Year_Birth if Age present to avoid duplication
if "Age" in df.columns and "Year_Birth" in features:
    features.remove("Year_Birth")

X = df[features].copy()
print("Features used for clustering:", features)



#4. Choose optimal number of clusters using Elbow method.

df_cluster = df[['Income', 'Age', 'TotalChildren', 'Recency', 'TotalSpent']].dropna()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df_cluster)

inertia = []
sil_scores = []
K = range(2, 11)
for k in K:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    inertia.append(kmeans.inertia_)
    sil_scores.append(silhouette_score(X_scaled, kmeans.labels_))

# Plot elbow + silhouette
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.plot(K, inertia, 'bo-')
plt.title('K-Means Elbow Curve')
plt.xlabel('k'), plt.ylabel('Inertia')

plt.subplot(1, 2, 2)
plt.plot(K, sil_scores, 'go-')
plt.title('Silhouette Score')
plt.xlabel('k'), plt.ylabel('Score')
plt.tight_layout()
plt.show()

#5. Apply K-Means clustering.

kmeans = KMeans(n_clusters=4, random_state=42)
df_cluster['KMeans_Cluster'] = kmeans.fit_predict(X_scaled)

df_cluster

#6. Apply Hierarchical clustering and compare.

linked = linkage(X_scaled, method='ward')
plt.figure(figsize=(10, 5))
dendrogram(linked, truncate_mode='lastp', p=10)
plt.title("Dendrogram")
plt.xlabel("Samples")
plt.ylabel("Distance")
plt.show()

df_cluster['Hierarchical_Cluster'] = fcluster(linked, t=4, criterion='maxclust')

df_cluster

ct = pd.crosstab(df_cluster["KMeans_Cluster"], df_cluster["Hierarchical_Cluster"])
print("\nCross-tabulation KMeans vs Hierarchical:\n", ct)

# Optional: Compare clusters
print(df_cluster[['KMeans_Cluster', 'Hierarchical_Cluster']].value_counts())



#7. Visualize clusters using PCA or t-SNE.

pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_scaled)

plt.figure(figsize=(6,4))
for lab in np.unique(df_cluster['KMeans_Cluster']):
    mask = df_cluster['KMeans_Cluster']==lab
    plt.scatter(X_pca[mask,0], X_pca[mask,1], label=f"Cluster {lab}", s=10)
plt.title("KMeans clusters visualized with PCA (2 components)")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.legend(markerscale=2, bbox_to_anchor=(1.05, 1), loc='upper left')
plt.show()

import plotly.express as px
from sklearn.decomposition import PCA

#df = px.data.iris()
#X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]

#pca = PCA(n_components=3)
#components = pca.fit_transform(X)

total_var = pca.explained_variance_ratio_.sum() * 100

fig = px.scatter_3d(
    X_scaled, x=0, y=1, z=2, color=df_cluster['KMeans_Cluster'],
    title=f'Total Explained Variance: {total_var:.2f}%',
    labels={'0': 'PC 1', '1': 'PC 2', '2': 'PC 3'}
)
fig.show()



#8. Profile each cluster (age, income, loyalty).

# ---- CLUSTER PROFILING ----
# Add cluster labels to dataframe
df['Cluster'] = kmeans.labels_

# Compute age
df['Age'] = 2024 - df['Year_Birth']

# 'Loyalty' = Years since they became customer
df['Loyalty'] = 2024 - df['Dt_Customer'].dt.year

# Profile summary
cluster_profile = df.groupby('Cluster').agg({
    'Age': 'mean',
    'Income': 'mean',
    'Loyalty': 'mean',
    'MntWines': 'mean',
    'MntMeatProducts': 'mean',
    'MntFruits': 'mean',
    'MntFishProducts': 'mean',
    'MntGoldProds': 'mean',
    'NumWebPurchases': 'mean',
    'NumStorePurchases': 'mean'
}).round(2)

print(cluster_profile)



#9. Label original dataset with cluster IDs

# Save dataset with clusters
df.to_csv("customer_clusters.csv", index=False)



#10. Recommend marketing strategy per cluster.

df["MntTotal"] = (
    df["MntWines"] +
    df["MntFruits"] +
    df["MntMeatProducts"] +
    df["MntFishProducts"] +
    df["MntSweetProducts"] +
    df["MntGoldProds"]
)

cluster_profile = df.groupby('Cluster').agg({
    'Age': 'mean',
    'Income': 'mean',
    'MntTotal': 'mean',
})



df['Cluster'] = kmeans.labels_

cluster_summary = df.groupby('Cluster').agg({
    'Income': 'mean',
    'MntWines': 'mean',
    'MntMeatProducts': 'mean',
    'MntGoldProds': 'mean',
    'NumDealsPurchases': 'mean',
    'Recency': 'mean',
    'MntTotal': 'mean'
}).round(2)

print("===== CLUSTER SUMMARY =====")
display(cluster_summary)

def describe_cluster(row):
    desc = []

    # Income level
    if row['Income'] > df['Income'].mean():
        desc.append("High Income")
    else:
        desc.append("Low/Medium Income")

    # Spending level
    if row['MntTotal'] > df['MntTotal'].mean():
        desc.append("High Spenders")
    else:
        desc.append("Low Spenders")

    # Recency
    if row['Recency'] < df['Recency'].mean():
        desc.append("Recent active buyers")
    else:
        desc.append("Not recent buyers")

    return ", ".join(desc)

cluster_summary['Description'] = cluster_summary.apply(describe_cluster, axis=1)

print("===== CLUSTER DESCRIPTIONS =====")
display(cluster_summary[['Description']])

def marketing_strategy(desc):
    if "High Income" in desc and "High Spenders" in desc:
        return "Target premium offers, exclusive launches, loyalty rewards."

    if "High Income" in desc and "Low Spenders" in desc:
        return "Provide first-purchase coupons, retarget with personalized ads."

    if "Low/Medium Income" in desc and "High Spenders" in desc:
        return "Promote value combos, cross-selling, festival discounts."

    if "Low/Medium Income" in desc and "Low Spenders" in desc:
        return "Send price-drop alerts, affordable packs, cashback offers."

    return "General engagement campaigns."

cluster_summary['Marketing Strategy'] = cluster_summary['Description'].apply(marketing_strategy)

print("===== MARKETING ACTION POINTS =====")
display(cluster_summary[['Description', 'Marketing Strategy']])

