# -*- coding: utf-8 -*-
"""ass_gen_ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RD8drT7tzk-m5NEYzZ1IY6cuxoK9WvGW
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

df = pd.read_csv("customer_churn.csv")
df.head()

lcoder = LabelEncoder()
df['Churn'] = lcoder.fit_transform(df['Churn'])

X = df[['MonthlyCharges']]
y = df['Churn']

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.3, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

KNN = KNeighborsClassifier(n_neighbors=5)
Knn_model = KNN.fit(X_train,y_train)

y_pred = Knn_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("KNN Accuracy:", accuracy)



#QUESTION 2

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("customer_churn.csv")
df.head()

lcoder = LabelEncoder()
df['Churn'] = lcoder.fit_transform(df['Churn'])   # Yes=1, No=0

X = df[['MonthlyCharges']]
y = df['Churn']

X

y

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

Logistic_Regression = LogisticRegression()
LR_model = Logistic_Regression.fit(X_train,y_train)

# Predict probabilities
y_pred = LR_model.predict_proba(X_test)

# Calculate Log Loss
loss = log_loss(y_test, y_pred)
print("Log Loss:", loss)

